# -*- coding: utf-8 -*-
"""fetch_checkbook_spending.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbsTF0rWvYYrcXzbhRsjdQCvyw0lXxXZ
"""

import requests
import xml.etree.ElementTree as ET
from pathlib import Path
import csv

MAX_ROWS_TO_FETCH = 50000
PAGE_SIZE = 1000
API_URL = "https://www.checkbooknyc.com/api"


def build_request_xml(fiscal_year: int, records_from: int, max_records: int = PAGE_SIZE) -> str:
    return f"""
    <request>
      <type_of_data>Spending</type_of_data>
      <records_from>{records_from}</records_from>
      <max_records>{max_records}</max_records>
      <search_criteria>
        <criteria>
          <name>fiscal_year</name>
          <type>value</type>
          <value>{fiscal_year}</value>
        </criteria>
      </search_criteria>
      <response_columns>
        <column>agency</column>
        <column>fiscal_year</column>
        <column>issue_date</column>
        <column>payee_name</column>
        <column>document_id</column>
        <column>contract_id</column>
        <column>expense_category</column>
        <column>spending_category</column>
        <column>check_amount</column>
        <column>department</column>
        <column>mwbe_category</column>
        <column>industry</column>
        <column>emerging_business</column>
        <column>woman_owned_business</column>
        <column>budget_code</column>
      </response_columns>
    </request>
    """.strip()


def fetch_page(fiscal_year: int, records_from: int, page_size: int = PAGE_SIZE) -> str:
    xml_body = build_request_xml(fiscal_year, records_from, page_size)

    headers = {
        "Content-Type": "application/xml",
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Origin": "https://www.checkbooknyc.com",
        "Referer": "https://www.checkbooknyc.com/",
        "Connection": "keep-alive",
    }

    resp = requests.post(
        API_URL,
        data=xml_body.encode("utf-8"),
        headers=headers,
        timeout=60,
    )

    print("Status code:", resp.status_code)
    resp.raise_for_status()
    return resp.text


def parse_response(xml_text: str):
    root = ET.fromstring(xml_text)

    record_count_elem = root.find(".//record_count")
    total_count = int(record_count_elem.text) if record_count_elem is not None else None

    records = []
    for rec in root.iter():
        child_tags = {child.tag for child in rec}
        if "agency" in child_tags and "check_amount" in child_tags:
            row = {child.tag: (child.text or "").strip() for child in rec}
            records.append(row)

    return records, total_count


def main():
    fiscal_year = 2023
    raw_dir = Path("data/raw")

    all_rows = []
    records_from = 1

    while True:
        print(f"\nFetching records from {records_from}...")
        xml_text = fetch_page(fiscal_year, records_from, PAGE_SIZE)
        rows, total_count = parse_response(xml_text)

        print(f"Got {len(rows)} rows.")

        if not rows:
            break

        all_rows.extend(rows)
        records_from += PAGE_SIZE

        if len(all_rows) >= MAX_ROWS_TO_FETCH:
            print("Hit row limit.")
            all_rows = all_rows[:MAX_ROWS_TO_FETCH]
            break

        if total_count is not None and records_from > total_count:
            break

    if all_rows:
        csv_path = raw_dir / "checkbook_spending_FY2023.csv"
        with csv_path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=all_rows[0].keys())
            writer.writeheader()
            writer.writerows(all_rows)

        print(f"\nSaved {len(all_rows)} rows to {csv_path}")
    else:
        print("No data retrieved.")


main()

from google.colab import files
files.download("data/raw/checkbook_spending_FY2023.csv")